### ISSUE TITLE
kube-enforcer - signal SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by trevor-viljoen** [aquasecurity/aqua-helm#242]
When I attempt to deploy the helm chart for the kube-enforcer, I always get a `panic: runtime error: invalid memory address or nil pointer dereference` . We are using `5.3`. Below is the debug log for one of the pods.

```
Initializing Aqua Container Security Platform: KubeEnforcer {version 15 0 5.3.0 commit 6f689cbd compiled on Mar 09 2021 16:34:25 <nil>}
2021/04/05 18:23:19 Using the default value provided: 40, for: AQUA_AUDIT_BULKSIZE
2021/04/05 18:23:19 Using the default value provided: 5, for: AQUA_AUDIT_FLASHTIME_INTERVAL
2021/04/05 18:23:19 Using the default value provided: 1, for: AQUA_AUDIT_CACHECLEANTIME_INTERVAL
2021-04-05 18:23:19.197 INFO    logger/logger.go:137    Logger started with level DEBUG
2021-04-05 18:23:19.217 INFO    kubeclient/permissons.go:28     KubeEnforcer Per
                        {"Allowed": "true"}
2021-04-05 18:23:19.223 INFO    kubeclient/permissons.go:37     KubeEnforcer Per
                                {"Allowed": "true"}
2021-04-05 18:23:19.417 INFO    kubeclient/permissons.go:46     KubeEnforcer Per
                                {"Allowed": "true"}
2021-04-05 18:23:20.013 INFO    kubeclient/permissons.go:55     KubeEnforcer Per
                                {"Allowed": "true"}
2021-04-05 18:23:20.613 INFO    kubeclient/permissons.go:64     KubeEnforcer Per
                                        {"Allowed": "true"}
2021-04-05 18:23:21.213 INFO    kubeclient/permissons.go:73     KubeEnforcer Per
                                        {"Allowed": "true"}
2021-04-05 18:23:21.813 INFO    kubeclient/permissons.go:82     KubeEnforcer Per
                                {"Allowed": "true"}
2021-04-05 18:23:23.413 INFO    kubeclient/permissons.go:94     KubeEnforcer Per
                                        {"Allowed": "true"}
2021-04-05 18:23:23.413 INFO    kubenf/main.go:88       Connecting to Aqua Gateway
2021-04-05 18:23:23.413 INFO    kubenf/main.go:116      Registering as Admission controller
2021-04-05 18:23:23.413 DEBUG   grpcclient/client.go:127        Starting gRPC client
2021-04-05 18:23:23.413 INFO    grpcclient/client.go:316        Attempting to connect to management server via gRPC
2021-04-05 18:23:23.413 INFO    grpcclient/client.go:381        Successfully connected to the server via gRPC
2021-04-05 18:23:23.413 INFO    grpcclient/client.go:464        Registering Kube Enforcer with Gateway
2021-04-05 18:23:23.413 INFO    webhook/server.go:86    Listening to requests from kube-apiserver using https...
2021-04-05 18:23:23.413 INFO    webhook/server.go:78    Listening to requests from kube-apiserver using http...
⇨ https server started on [::]:8443
⇨ http server started on [::]:8080
2021-04-05 18:23:23.604 DEBUG   grpcclient/client.go:499        Successfully registered Kube Enforcer
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x13cc5df]

goroutine 108 [running]:
bitbucket.org/scalock/kube-enforcer/src/grpcclient.(*GatewayClient).setJWT(0xc0003b2120, 0x0)
        /go/src/bitbucket.org/scalock/kube-enforcer/src/grpcclient/client.go:526 +0x5f
bitbucket.org/scalock/kube-enforcer/src/grpcclient.(*GatewayClient).RegisterKubeEnforcer(0xc0003b2120, 0x0, 0x0, 0x0, 0x0)
        /go/src/bitbucket.org/scalock/kube-enforcer/src/grpcclient/client.go:517 +0xbe5
bitbucket.org/scalock/kube-enforcer/src/grpcclient.(*GatewayClient).connectToServer(0xc0003b2120, 0x1da84c0, 0xc0005b88c0, 0xc0005b88c0, 0xc000269070)
        /go/src/bitbucket.org/scalock/kube-enforcer/src/grpcclient/client.go:383 +0xbf6
bitbucket.org/scalock/kube-enforcer/src/grpcclient.(*GatewayClient).startClient(0xc0003b2120, 0x0, 0x0)
        /go/src/bitbucket.org/scalock/kube-enforcer/src/grpcclient/client.go:211 +0x11f
bitbucket.org/scalock/kube-enforcer/src/grpcclient.(*GatewayClient).connect(0xc0003b2120)
        /go/src/bitbucket.org/scalock/kube-enforcer/src/grpcclient/client.go:152 +0x6e
bitbucket.org/scalock/kube-enforcer/src/grpcclient.(*GatewayClient).Start(0xc0003b2120, 0x0, 0x0)
        /go/src/bitbucket.org/scalock/kube-enforcer/src/grpcclient/client.go:130 +0xf4
main.main.func1.3(0xc00035fee0, 0xc000280600)
        /go/src/bitbucket.org/scalock/kube-enforcer/src/kubenf/main.go:139 +0x39
created by main.main.func1
        /go/src/bitbucket.org/scalock/kube-enforcer/src/kubenf/main.go:138 +0xb76
```

**Comment by psr031** [comment]
@trevor-viljoen 
Could you provide the version of GW the KE is connecting to?

**Comment by trevor-viljoen** [comment]
@psr031 The Gateway version is 5.3.0.

**Comment by psr031** [comment]
@trevor-viljoen Can you get us the exact version? Is it just 5.3.0? You can find version from UI ('Administration' => 'Aqua Gateways'). 

If GW and KE versions are different, can you upgrade GW/KE to the same version and check?

**Comment by trevor-viljoen** [comment]
@psr031 5.3.0 is the exact version of the gateway. We have an support ticket open and are waiting for those responsible for the gateway and the Aqua Control Plane. They are supposed to upgrade to 5.3.21097.

**Comment by semyonmor** [comment]
Is it still relevant or could be closed?

**Comment by semyonmor** [comment]
@psr031  If this issue is still relevant please reopen it
