### ISSUE TITLE
External Postgres-Database doesn't work

### ISSUE THREAD

**Issue by jewelt** [aquasecurity/aqua-helm#257]
We would like to run our AquaSec with an external database. However, we have a problem with the connection: 

# Our external Postgres database: 

- Version: 13.2
- No access is given to the "postgres" database. The pg_hba.conf does not allow access to the database "postgres".
- An "aquapolicy" and "aquaaudit" database have been created respectively. These are accessible from the Kubernetes cluster.

# Aqua Sec Deployment: 

In values.yaml, the corresponding database names have been set to the above. The following is in the environment variables: 
```
SCALOCK_GATEWAY_PUBLIC_IP	aqua-gateway-svc
SCALOCK_DBUSER	aquapolicy
SCALOCK_DBSSL	require
SCALOCK_DBPORT	
SCALOCK_DBNAME	aquapolicy
SCALOCK_DBHOST	postgre01-dev.company.tld
SCALOCK_AUDIT_DBUSER	aquaaudit
SCALOCK_AUDIT_DBSSL	require
SCALOCK_AUDIT_DBPORT	
SCALOCK_AUDIT_DBNAME	aquaaudit
SCALOCK_AUDIT_DBHOST	postgre01-dev.company.tld
```

The log of the gateway container contains the following: 

```
2021-04-28 15:12:31.616              INFO     logger/logger.go:135     Logger started with level DEBUG

2021-04-28 15:12:31.616              INFO     clibase/clibase.go:92      Initializing Aqua CSP Gateway   {"version": "6.0.21083"}

2021-04-28 15:12:31.616              INFO     logger/logger.go:135     Trying to connect to Postgres DB Host [postgre01-dev.company.tld]

2021-04-28 15:12:31.623              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (dial tcp COMPANY_POSTGRES_SERVER_IP:5432: connect: connection refused), retry #1 trying again in 1 second...

2021-04-28 15:12:32.641              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (dial tcp COMPANY_POSTGRES_SERVER_IP:5432: connect: connection refused), retry #2 trying again in 1 second...

2021-04-28 15:12:33.668              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #3 trying again in 1 second...

2021-04-28 15:12:34.685              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #4 trying again in 1 second...

2021-04-28 15:12:35.704              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #5 trying again in 1 second...

2021-04-28 15:12:36.722              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #6 trying again in 1 second...

2021-04-28 15:12:37.741              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #7 trying again in 1 second...

2021-04-28 15:12:38.755              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #8 trying again in 1 second...

2021-04-28 15:12:39.772              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #9 trying again in 1 second...

2021-04-28 15:12:40.790              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #10 trying again in 1 second...

2021-04-28 15:12:41.820              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #11 trying again in 1 second...

2021-04-28 15:12:42.839              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #12 trying again in 1 second...

2021-04-28 15:12:43.869              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #13 trying again in 1 second...

2021-04-28 15:12:44.886              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #14 trying again in 1 second...

2021-04-28 15:12:45.902              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #15 trying again in 1 second...

2021-04-28 15:12:46.919              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #16 trying again in 1 second...

2021-04-28 15:12:47.934              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #17 trying again in 1 second...

2021-04-28 15:12:48.953              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #18 trying again in 1 second...

2021-04-28 15:12:49.970              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #19 trying again in 1 second...

2021-04-28 15:12:50.988              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #20 trying again in 1 second...

2021-04-28 15:12:52.006              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #21 trying again in 1 second...

2021-04-28 15:12:53.026              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #22 trying again in 1 second...

2021-04-28 15:12:54.043              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #23 trying again in 1 second...

2021-04-28 15:12:55.061              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #24 trying again in 1 second...

2021-04-28 15:12:56.077              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #25 trying again in 1 second...

2021-04-28 15:12:57.095              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #26 trying again in 1 second...

2021-04-28 15:12:58.115              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #27 trying again in 1 second...

2021-04-28 15:12:59.129              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #28 trying again in 1 second...

2021-04-28 15:13:00.147              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #29 trying again in 1 second...

2021-04-28 15:13:01.162              WARN  logger/logger.go:143     Can't establish connection to DB Host postgre01-dev.company.tld (pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an), retry #30 trying again in 1 second...

2021-04-28 15:13:02.162              PANIC   logger/logger.go:127     Could not establish connection to DB postgre01-dev.company.tld: pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an

bitbucket.org/scalock/server/common/logger.Panicf

                /go/src/bitbucket.org/scalock/server/common/logger/logger.go:127

bitbucket.org/scalock/server/common/datastore/slkdb.(*dbConnection).connectToDB

                /go/src/bitbucket.org/scalock/server/common/datastore/slkdb/db_connector.go:493

bitbucket.org/scalock/server/common/datastore/slkdb.(*dbConnection).Connect

                /go/src/bitbucket.org/scalock/server/common/datastore/slkdb/db_connector.go:240

bitbucket.org/scalock/server/common/datastore/slkdb.(*dbs).ConnectScalockDB

                /go/src/bitbucket.org/scalock/server/common/datastore/slkdb/dbs.go:156

main.glob..func1

                /go/src/bitbucket.org/scalock/server/sedocksrv/sedocksrv.go:75

bitbucket.org/scalock/server/vendor/github.com/spf13/cobra.(*Command).execute

                /go/src/bitbucket.org/scalock/server/vendor/github.com/spf13/cobra/command.go:766

bitbucket.org/scalock/server/vendor/github.com/spf13/cobra.(*Command).ExecuteC

                /go/src/bitbucket.org/scalock/server/vendor/github.com/spf13/cobra/command.go:852

bitbucket.org/scalock/server/vendor/github.com/spf13/cobra.(*Command).Execute

                /go/src/bitbucket.org/scalock/server/vendor/github.com/spf13/cobra/command.go:800

main.main

                /go/src/bitbucket.org/scalock/server/sedocksrv/sedocksrv.go:223

runtime.main

                /usr/local/go/src/runtime/proc.go:203

panic: Could not establish connection to DB postgre01-dev.company.tld: pq: kein pg_hba.conf-Eintrag für Host »COMPANY_SERVER_IP«, Benutzer »aquapolicy«, Datenbank »postgres«, SSL an

goroutine 1 [running]:

bitbucket.org/scalock/server/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0005bc0b0, 0x0, 0x0, 0x0)

                /go/src/bitbucket.org/scalock/server/vendor/go.uber.org/zap/zapcore/entry.go:229 +0x546

bitbucket.org/scalock/server/vendor/go.uber.org/zap.(*Logger).Panic(0xc000392c60, 0xc0009624d0, 0xaa, 0x0, 0x0, 0x0)

                /go/src/bitbucket.org/scalock/server/vendor/go.uber.org/zap/logger.go:225 +0x7f

bitbucket.org/scalock/server/common/logger.Panicf(0x2f5720a, 0x2b, 0xc00098f4b8, 0x2, 0x2)

                /go/src/bitbucket.org/scalock/server/common/logger/logger.go:127 +0x8c

bitbucket.org/scalock/server/common/datastore/slkdb.(*dbConnection).connectToDB(0xc0001620e0, 0x40e9f6)

                /go/src/bitbucket.org/scalock/server/common/datastore/slkdb/db_connector.go:493 +0x705

bitbucket.org/scalock/server/common/datastore/slkdb.(*dbConnection).Connect(0xc0001620e0, 0x2edbf88, 0x3, 0x3668cc0)

                /go/src/bitbucket.org/scalock/server/common/datastore/slkdb/db_connector.go:240 +0x40

bitbucket.org/scalock/server/common/datastore/slkdb.(*dbs).ConnectScalockDB(0xc0003fa5a0, 0x2edbf88, 0x3, 0x0, 0x0)

                /go/src/bitbucket.org/scalock/server/common/datastore/slkdb/dbs.go:156 +0x4b3

main.glob..func1(0x5003a00, 0x50da660, 0x0, 0x0)

                /go/src/bitbucket.org/scalock/server/sedocksrv/sedocksrv.go:75 +0x11d

bitbucket.org/scalock/server/vendor/github.com/spf13/cobra.(*Command).execute(0x5003a00, 0xc00004e1d0, 0x0, 0x0, 0x5003a00, 0xc00004e1d0)

                /go/src/bitbucket.org/scalock/server/vendor/github.com/spf13/cobra/command.go:766 +0x2aa

bitbucket.org/scalock/server/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x5003a00, 0x5003c60, 0xc000733f50, 0x407d2f)

                /go/src/bitbucket.org/scalock/server/vendor/github.com/spf13/cobra/command.go:852 +0x2ea

bitbucket.org/scalock/server/vendor/github.com/spf13/cobra.(*Command).Execute(...)

                /go/src/bitbucket.org/scalock/server/vendor/github.com/spf13/cobra/command.go:800

main.main()

                /go/src/bitbucket.org/scalock/server/sedocksrv/sedocksrv.go:223 +0x31
```

The same error messages can also be found in the database log. 

However, a basic login via psql command from the container-shell is possible: 

```
opt/aquasec $ psql -U aquapolicy -h postgre01-dev.company.tld -d aquapolicy

Password for user aquapolicy:

psql (12.6, server 13.2)

WARNING: psql major version 12, server major version 13.

         Some psql features might not work.

SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)

Type "help" for help.

 

aquapolicy=>
```

This means we suspect that aquasec is not addressing the correct database. So, it does not take aquapolicy but postgres.

**Comment by KoppulaRajender** [comment]
@jewelt - It's working, Not able to reproduce the issue with postgres user. 

`No access is given to the "postgres" database. The pg_hba.conf does not allow access to the database "postgres".`
Seems you mentioned no access to postgres DB, then you must declare the MAINTANANCE_DB env variable if the default "postgres" db is not accessible.

https://github.com/aquasecurity/aqua-helm/blob/0df38a932d12b0c09f62a07b020d9e1d46adc3b3/server/values.yaml#L279


Closing, for now still the issue persists please reopen.
